# Generated by Django 2.2 on 2020-10-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('statu', models.CharField(choices=[('ожидание', 'Ожидание'), ('виполнен', 'Виполнен'), ('оплачен', 'Оплачен')], default='Ожидание', max_length=10, verbose_name='статус заказа')),
            ],
            options={
                'verbose_name': 'Статус Заказа',
                'verbose_name_plural': 'Статус Заказов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, verbose_name='товар')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
                ('added_product', models.DateTimeField(auto_now_add=True)),
                ('update_product', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(default=0, verbose_name='скидка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='sales_consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ожидание', 'Ожидание'), ('виполнен', 'Виполнен')], default='Ожидание', max_length=10, verbose_name='статус заказа')),
                ('kanban1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.Product', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('ожидание', 'Ожидание'), ('оплачен', 'Оплачен')], default='Ожидание', max_length=10, verbose_name='статус заказа')),
                ('kanban2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.Product', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='accountant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanban3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.Product', verbose_name='товар')),
                ('kanban4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.deal', verbose_name='статус')),
            ],
        ),
    ]
